Add translations of GAM plot legend
inbo/aspbo pull request #108
Opened 2024-04-09 14:55 UTC by soriadelva

The translations of the GAM legend have been added to the translations.csv file.

2024-04-09 15:22 UTC, SanderDevisscher requested changes
@soriadelva er is volgens mij iets fout gelopen met het inlezen en/of wegschijven van de file. Er is namelijk een titelloze rijnummer kolom toegevoegd en de delimiter van het bestand is gewijzigd van ";" naar ",". 

Waarmee heb je het geopend ? Hoe heb je het weggescherven ? 

`readr::read_csv2("https://raw.githubusercontent.com/inbo/aspbo/uat/data/output/UAT_direct/translations.csv")` en `readr::write_csv2("./data/output/UAT_direct/translations.csv")` zouden deze issues niet mogen hebben. 

Alternatief kan je het openen in rstudio, met kladblok of notepad++

2024-04-09 16:54 UTC, soriadelva commented
> @soriadelva er is volgens mij iets fout gelopen met het inlezen en/of wegschijven van de file. Er is namelijk een titelloze rijnummer kolom toegevoegd en de delimiter van het bestand is gewijzigd van ";" naar ",".
> 
> Waarmee heb je het geopend ? Hoe heb je het weggescherven ?
> 
> `readr::read_csv2("https://raw.githubusercontent.com/inbo/aspbo/uat/data/output/UAT_direct/translations.csv")` en `readr::write_csv2("./data/output/UAT_direct/translations.csv")` zouden deze issues niet mogen hebben.
> 
> Alternatief kan je het openen in rstudio, met kladblok of notepad++

Hmm vreemd, dat moet bijna tijdens het importeren gebeurd zijn. Ik herdoe het direct eens!

2024-04-09 17:13 UTC, soriadelva commented
@SanderDevisscher nu zou het wel moeten kloppen, sorry!

2024-04-09 18:26 UTC, SanderDevisscher commented
@soriadelva looks a lot better 😄 
@mvarewyck can you confirm NA's in empty fields won't cause any issues ?

2024-04-10 07:57 UTC, mvarewyck commented
>@mvarewyck can you confirm NA's in empty fields won't cause any issues ?

I've updated the code such that it can handle NA values.
https://github.com/inbo/alien-species-portal/pull/74/commits/c8a43f06ef3102882f1078b3f290b025f29a7213

2024-04-11 09:11 UTC, SanderDevisscher approved these changes
👍

2024-04-11 09:11 UTC, merged