199 rework timeseries creation to contain species with observation after 1950
inbo/aspbo pull request #202
Opened 2024-07-03 13:56 UTC by soriadelva

2024-07-09 11:12 UTC, SanderDevisscher commented
success 💪 🥳

2024-07-15 18:16 UTC, soriadelva commented
@SanderDevisscher deze PR mag gereviewed worden, nu de flow weer werkt :)

2024-07-17 09:04 UTC, SanderDevisscher requested changes
Since we changed the name of this script to cube_preprocessing (see #201) it is best to do the following (in order): 

- [x] rename 05_occurrence_indicators_preprocessing.Rmd to cube_preprocessing on this branch
- [x] do a rebase to make sure other changes in cube_preprocessing are included
- [x] solve possible conflicts
- [ ] solve other issues

2024-07-17 09:04 UTC, SanderDevisscher commented on src/05_occurrence_indicators_preprocessing.Rmd
rename to cube_preprocessing.Rmd

2024-07-17 09:04 UTC, SanderDevisscher commented on src/05_occurrence_indicators_preprocessing.Rmd
>  ```{r select_aliens_after_year_of_introduction}
select aliens with recent observations?

2024-07-17 09:04 UTC, SanderDevisscher commented on src/05_occurrence_indicators_preprocessing.Rmd
>  ```{r recent_alien_species}
extinct_alien_species ?

2024-07-17 09:04 UTC, SanderDevisscher commented on src/05_occurrence_indicators_preprocessing.Rmd
>  ```{r save_old_introduced_taxa_as_tsv_file}
save_last_observed_before ?

2024-07-17 14:26 UTC, soriadelva commented
Rebase with uat?

2024-07-17 14:26 UTC, SanderDevisscher commented
> Rebase with uat?

yes

2024-07-17 14:28 UTC, soriadelva commented
> > Rebase with uat?
> 
> yes

I got the following error: A lock file already exists in the repository, which blocks this operation from completing. any ideas?

2024-07-19 08:41 UTC, SanderDevisscher approved these changes

2024-07-19 08:41 UTC, merged