246 update inputs
inbo/aspbo pull request #259
Opened 2024-10-02 06:11 UTC by jrhillae

@SanderDevisscher: dit zijn mijn belangrijkste wijzigingen. Ik heb nog 2 opmerkingen:

- iNaturalist data wordt enkel gebruikt voor het kaartje? Wordt verspreidingsdata van andere soorten op exotenportaal ook standaard aangevuld met iNaturalist data? Veel van Vespa-Watch data (tot 2 november 2022) staat al op iNaturalist. En van Waarnemingen lezen we enkel nesten in vanaf 13/6/2024, dus ervoor staat het niet in onze databank. Eventueel enkel data van binnen Vespa-Watch inlezen? Ik weet dat ik vroeger een kaartje wou van zowel waarnemingen als Vespa-Watch omdat we toen nog niet waren samengevoegd maar dit zijn we momenteel wel, dus de nood om data van andere databanken naast Vespa-Watch weer te geven is nu minder.

- de actieve haardenkaart gaat normaal toch worden aangepast naar enkel een hot map van observaties van individuen de laatste 2 weken? Ok als ik de flow voor nesten kopieer in een nieuwe map op Vespa R en dat we die gebruiken om individuen dagelijks op te laden via API uit Waarnemingen +2en in Google Sheet weg te schrijven? Als ik 1 lijntje in API aanpas en link naar Google sheet zou dit voldoende moeten zijn, maar moeten jullie automatisatie wss wel nog aanpassen ook ;).

- Is er een speciale deadline maandag dat je tegen dan wou dat ik dit reviewde? De output van update_inputs pas ik nog verder aan om in te lezen in vespa-db, deze wordt normaal in oktober gelanceerd. Na de launch kan ik de code geven om te nesten via API uit vespa-db te halen en kan update-inputs worden aangepast naar deze databank :), normaal nog dit jaar dus.

2024-10-02 07:12 UTC, SanderDevisscher requested changes
In nesten.geojson komt "ongekend" voor in de kolom provincie. Dit moet "onbekend" worden.

2024-10-02 07:44 UTC, SanderDevisscher commented
Ik disable de action tot de flow vanaf de vespadb uitgeklaard is.
De management pagina van vespa laat ik ook tijdelijk uitschakelen door @mvarewyck.

2024-10-02 07:49 UTC, SanderDevisscher approved these changes, later dismissed

2024-10-02 07:50 UTC, SanderDevisscher commented
@soriadelva kijk jij deze pr eens na aub

2024-10-02 09:09 UTC, jrhillae commented
@SanderDevisscher, @soriadelva: ik heb iets bizar opgemerkt in de data ik ga de code nog eens nakijken. Ik wou het naar draft converteren maar dat lukte niet. Bij deze ;)

2024-10-07 06:51 UTC, jrhillae commented
@soriadelva, @SanderDevisscher: ik heb het foutje gevonden en gecorrigeerd. De 2 tabellen (aantal nesten per provincie per jaar en aantal nesten per jaar per maand) kloppen nu. Tot op het punt dat data_nest_final_vlaanderen en deze tabellen zijn gemaakt werkt de code. Erna komt er code gelinkt aan exotenportaal en heb ik niet langer gecontroleerd.

2024-10-07 12:42 UTC, SanderDevisscher approved these changes
@jrhillae het stuk code voor het exotenportaal is te bekijken als de we de datastroom herwerken naar de de vespadb. De action is uitgeschakkeld (https://github.com/inbo/aspbo/actions/workflows/get_vespa_velutina_management.yaml) en de vespa velutina management pagina zal gedeactiveerd worden op het exotenportaal https://github.com/inbo/alien-species-portal/issues/121. 

Ik ga ervan uit dat je wijzigingen kloppen, als je zelf overtuigd bent mag je deze branch mergen 😉

2024-10-07 13:38 UTC, merged