295 create faq page
inbo/aspbo pull request #303
Opened 2024-12-20 13:02 UTC by SanderDevisscher

fixes #295 

@mvarewyck FYI, linked to https://github.com/inbo/alien-species-portal/issues/125

2025-03-14 12:14 UTC, SanderDevisscher commented
@soriadelva can you please review this PR?

2025-04-04 12:24 UTC, soriadelva commented
> @soriadelva can you please review this PR?

Ik bekijk het!

2025-04-04 13:19 UTC, soriadelva requested changes
I mostly reviewed the english and dutch FAQ pages. For the French one, it may be good to let Lynn go over it. Some minor typos and suggestions, otherwise it looks good!

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +can be found in the top right of the graph.</p>
I would rephrase this: This button can be found in the top right corner of the graph

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +left of the map.</p>
same here: This button can be found in the bottom left corner of the map.

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +‘share link’ button. This can be found in the top right of the page.</p>
Rephrase: This button can be found in the top right corner of the page.

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +the bottom left of the page.</p>
Rephrase: This button can be found in the bottom left corner of the page.

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +<p>TrIAS will bring together the expertise and knowledge of 9 ongoing
I would leave out the future tense, as TrIAS has already been done: TrIAS brings together... 

9 --> nine

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +objective of TrIAS is to be able to predict the invasion risk of alien
A crucial objective of TrIAS is to predict...

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +Correlative species distribution models (SDMs) will be used to create
Correlative species distribution models are used... (changing the tense)

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +climate layers for Belgium published by the KMI will be used.</p>
I would leave this last line out, since we will very soon stop using the KMI layers.

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_fr.html
> +seront utilisés.</p>
Hier zou ik ook het laatste lijntje weglaten

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +links onder de meeste grafieken, tabelen of kaarten.</p>
Fix typo: tabe**l**len

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +klikken. Deze vind u rechtsboven de grafiek.</p>
Fix typo: deze vind**t** u. Ook hoveren zou ik anders verwoorden, bvb: Dit kan door met de muis over de grafiek te bewegen en op het ‘fototoestel’-icoon te klikken. Deze vindt u rechtsboven de grafiek

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +op de ‘download kaart’ knop te klikken. Deze vind u links onder de
Fix typo: Deze vind**t** u
Voeg koppelteken toe: 'download kaart'-knop

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +te klikken. Deze vind u rechtsboven de pagina.</p>
Fix typo: deze vind**t** u

Voeg koppelteken toe: 'deel link'-knop

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +<p>Het is mogelijk om een PDF rapport te downloaden van soortinformatie
Gebruik koppelteken: PDF-rapport en 'create report'-knop
Ik zou het herformuleren als: Het is mogelijk om een PDF-rapport te downloaden **met** soortinformatie **over** de gekozen soort. Dit rapport **be**vat alle soortspecifieke grafieken, tabellen en kaarten en de bij**be**horende instellingen. U kunt dit rapport aanmaken door op de 'create report'-knop te klikken. Deze vind**t** u linksonder **op** de pagina.

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +<h3>Wat is de TrIAS?</h3>
Laat 'de' weg: Wat is TrIAS?

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +<p>TrIAS zal de expertise en kennis van 9 lopende en voorbije BELSPO
Ook hier zou ik de toekomstige tijd weglaten, gezien TrIAS al gebeurd is: TrIAS brengt de expertise en kennis van **negen** lopende en voorbije BELSPO projecten samen:  Alien Alert, Invaxen, Diars, INPLANBEL, Alien Impact, Ensis, CORDEX.be, Speedy en het Belgisch Biodiversiteitsplatform.

Nummers onder de 10 worden voluit geschreven

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +uitheemse soorten in respons op klimaatverandering te kunnen
'kunnen' weglaten

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +verschillende toekomstige emissiescenario’s. Hiervoor wordt gebruik
Laatste zin weglaten

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +voorspellen. Correlatieve soortverspreidingsmodellen (SDM’s) zullen
zullen gebruikt worden --> worden gebruikt

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_fr.html
> +<p>TrIAS réunira l’expertise et les connaissances de 9 projets BELSPO en
9 --> neuf, en ook hier toekomstige tijd weglaten réunira --> réunit

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_fr.html
> +corrélatifs (SDM) seront utilisés pour créer des cartes de risque sous
seront utilisés --> sont utilisés

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +downloaden via de ‘download data’ knop. Deze knop is te vinden in de
Voeg koppelteken toe: 'download data'-knop

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +<p>Het is mogelijk om ontbrekende gegevens te melden via de ‘contact’
Voeg koppelteken toe: 'contact'-knop

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_nl.html
> +ontwikkelen van datagestuurde procedures voor risico-analyse gebaseerd
risico-analyse--> risicoanalyse

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +<p>It is possible to report missing data via the ‘contact’ button. This
Misschien iets vlotter maar niets mis mee: You can report...

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +<p>It is possible to export graphs and maps as an image. This can be
an image --> images (since you refer to graphs and maps, this has to be plural too)

2025-04-04 13:19 UTC, soriadelva commented on HTML_pages/HTML/FAQ_en.html
> +<p>It is possible to export maps as an image. This can be done by
an image--> images

2025-04-04 13:49 UTC, SanderDevisscher commented on HTML_pages/HTML/FAQ_en.html
> +<p>It is possible to report missing data via the ‘contact’ button. This
I left it for now

2025-04-04 13:53 UTC, SanderDevisscher commented
@LynnPallemaerts are you willing to check the french translation ? 
@soriadelva I've implemented most of the change requests. Can you rereview ?

2025-04-04 14:09 UTC, soriadelva requested changes

2025-04-04 14:09 UTC, soriadelva commented on HTML_pages/Rmd_files/faq.Rmd
> +Het is mogelijk om grafieken en kaarten te exporteren als afbeelding. Dit kan door met de muis over de grafiek te bewegen en op het 'fototoestel'-icoon te klikken. Dit icoon vind u rechtsboven de gra
Vind u --> vindt u
afbeelding --> afbeeldingen

2025-04-04 14:09 UTC, soriadelva commented on HTML_pages/Rmd_files/faq.Rmd
> +Het is mogelijk om een PDF-rapport te downloaden van soortinformatie van de gekozen soort. Dit rapport omvat alle soortspecifieke grafieken, tabellen en kaarten en de bijhorende instellingen. Dit rap
van soortinformatie van de gekozen soort --> met soortinformatie over de gekozen soort.  Of met informatie over de gekozen soort (klinkt misschien nog wat vlotter, maar kies maar)

2025-04-04 14:09 UTC, soriadelva commented on HTML_pages/Rmd_files/faq.Rmd
> +TrIAS brengt de expertise en kennis van negen lopende en voorbije BELSPO projecten samen: Alien Alert, Invaxen, Diars, INPLANBEL, Alien Impact, Ensis, CORDEX.be, Speedy en het Belgisch Biodiversiteit
Ik zou die laatste zin toch weglaten, want de IPCC scenario's en land use maps zijn maar een heel klein deel van de workflow. Het klinkt wat vreemd omdat het nu lijkt of de workflow specifiek op die dingen draait (ik zou het ook weglaten in de EN en FR pagina's)

2025-04-04 14:09 UTC, soriadelva commented on HTML_pages/Rmd_files/faq.Rmd
> +Het is mogelijk om kaarten te exporteren als afbeelding. Dit kan door op de 'download kaart'-knop te klikken. Deze knop vindt u links onder de kaart.
afbeelding --> afbeeldingen

2025-04-04 14:09 UTC, soriadelva commented on HTML_pages/Rmd_files/faq.Rmd
> +It is possible to export maps as an image. This can be done by clicking on the 'download map' button. This button can be found in the bottom left corner of the map.
an image --> images

2025-04-04 14:09 UTC, soriadelva commented on HTML_pages/Rmd_files/faq.Rmd
> +It is possible to download a PDF report of the species information of the chosen species. This report includes all species-specific graphs, tables and maps and their associated settings. This report
Misschien selected species ipv chosen species (maar mss eerder personal preference, je kiest maar).

2025-04-04 14:16 UTC, SanderDevisscher commented
all done 😄

2025-04-04 14:26 UTC, soriadelva approved these changes

2025-04-04 14:27 UTC, merged